name: Rust build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Get rust tool chain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v2
      - name: cargo build release
        run: cargo build --release --all-features
      - name: cargo test all
        run: cargo test --all-targets --all-features
      - name: cargo clippy warning
        run: cargo clippy --no-deps
      - name: cargo fmt check
        run: cargo fmt --check
